name: 'decode-base64-github-action'
description: >
  This action sets a Base64 string to an environment variable or writes it to a file.
inputs:
  base64:
    description: >
      Specifies a Base64 string to decode.
    required: true
  environment:
    description: >
      To also set the decoded string to an environment variable, specify the name of the environment variable in this parameter.
      If this value is set, the environment variable will be set to the decoded result.
      If omitted, the environment variable will not be set.
    required: false
    default: ''
  output-path:
    description: >
      To output the decoded string to the specified file, specify a path in this parameter.
      If omitted, the internally set path is used and passed to `outputs.output-path`.
    required: false
    default: ''
outputs:
  decoded:
    description: >
      The decoded string is set.
  output-path:
    description: >
      The file path where the decoded string was written out.
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: "download"
  color: "orange"