name: Test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  Test:
    runs-on: ${{ matrix.OS }}
    timeout-minutes: 5
    strategy:
      matrix:
        OS: [ ubuntu-latest, macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v4

      - uses: ./
        id: decode-base64-1
        with:
          base64: ${{ secrets.BASE64 }}
      - name: Default Output
        run: |
          echo "Output=${{ steps.decode-base64-1.outputs.decoded }}"

      - uses: ./
        id: decode-base64-2
        with:
          base64: ${{ secrets.BASE64 }}
      - name: Default Output path
        run: |
          echo "Path=${{ steps.decode-base64-2.outputs.output-path }}"
          cat ${{ steps.decode-base64-2.outputs.output-path }}

      - uses: ./
        id: decode-base64-3
        with:
          base64: ${{ secrets.BASE64 }}
          output-path: ${{ runner.temp }}/tmp.txt
      - name: Output file path specification
        run: |
          echo "Path=${{ steps.decode-base64-3.outputs.output-path }}" 
          cat ${{ steps.decode-base64-3.outputs.output-path }}

      - uses: ./
        with:
          base64: ${{ secrets.BASE64 }}
          environment: DECODED
      - name: Output environment
        run: |
          echo "Environemt=$DECODED"
